sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
addons:
install:
  - pip install tox-travis pytest pexpect mock coveralls
script:
  - coverage run --source=splitcpy setup.py test
after_success:
  - coveralls
