sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy3"
addons:
install:
  - pip install tox-travis pytest pexpect mock coveralls
script:
  python -m coverage run --source=splitcpy setup.py test
after_success:
  coveralls
