#!/bin/sh

for repo in splitcpyppa ; do
    for pkg in splitcpy ; do
        reprepro -Vb . --ignore=wrongdistribution includedeb $repo ../../$pkg\_*_all.deb
    done
done

rm -rf db/

#rm -f dists/sid
#ln -s ./unstable dists/sid
#rm -f dists/jessie
#ln -s ./testing dists/jessie
#rm -f dists/wheezy
#ln -s ./stable dists/wheezy
